import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Button } from 'antd';

const Home = () => (
	<>
		<Head>
			<title>Create Next App</title>
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />
		</Head>
		<div>
			<Button>I am a button.</Button>
		</div>
	</>
);

export default Home;
